[env:d_grape_test_motors]
platform  = ststm32
board     = disco_f407vg
framework = stm32cube

upload_protocol = stlink
debug_tool      = stlink

board_build.f_cpu = 168000000L

extra_scripts = pre:extra_scripts.py

lib_extra_dirs = lib

monitor_speed = 115200
monitor_port  = COM3
monitor_filters = direct

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F407xx
    "-DCMSIS_device_header=\"stm32f4xx.h\""
    -std=gnu11
    -Iinclude
    -Ilib/usb_cdc
    -Ilib/encoders
    -Ilib/pid
    -Ilib/motors
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,-u,_printf_float

lib_ignore =
    AUDIO
    CCID
    CDC_ECM
    CDC_RNDIS
    CustomHID
    DFU
    MSC
    MTP
    Printer
